// Generated by CoffeeScript 1.12.7
(function() {
  var StorageMemory;

  StorageMemory = (function() {
    function StorageMemory() {
      this.codeHashes = {};
    }

    StorageMemory.prototype.addHash = function(hash, file, line, language) {
      var ref;
      this.codeHashes[language] = (ref = this.codeHashes[language]) != null ? ref : {};
      return this.codeHashes[language][hash] = {
        line: line,
        file: file
      };
    };

    StorageMemory.prototype.hasHash = function(hash, language) {
      return this.codeHashes[language] && hash in this.codeHashes[language];
    };

    StorageMemory.prototype.getHash = function(hash, language) {
      var ref;
      return (ref = this.codeHashes[language]) != null ? ref[hash] : void 0;
    };

    return StorageMemory;

  })();

  module.exports = StorageMemory;

}).call(this);
