// Generated by CoffeeScript 1.12.7
(function() {
  var Detector, Map;

  Map = require('./map').Map;

  Detector = (function() {
    function Detector(strategy) {
      this.strategy = strategy;
    }

    Detector.prototype.start = function(files, minLines, minTokens) {
      var file, i, len, map;
      if (files == null) {
        files = [];
      }
      if (minLines == null) {
        minLines = 5;
      }
      if (minTokens == null) {
        minTokens = 70;
      }
      map = new Map();
      for (i = 0, len = files.length; i < len; i++) {
        file = files[i];
        this.strategy.detect(map, file, minLines, minTokens);
      }
      return map;
    };

    return Detector;

  })();

  exports.Detector = Detector;

}).call(this);
