// Generated by CoffeeScript 1.12.7
(function() {
  var debugPreprocessor, logger;

  logger = require("winston");

  debugPreprocessor = function(jscpd) {
    var file, i, len, name, option, ref, ref1;
    if (jscpd.options.debug) {
      logger.info('----------------------------------------');
      logger.info('Options:');
      ref = jscpd.options;
      for (name in ref) {
        option = ref[name];
        if (name !== 'selectedFiles') {
          logger.info(name + " = " + option);
        }
      }
      logger.info('----------------------------------------');
      logger.info('Files:');
      ref1 = jscpd.options.selectedFiles;
      for (i = 0, len = ref1.length; i < len; i++) {
        file = ref1[i];
        logger.info(file);
      }
      logger.info('----------------------------------------');
      return logger.info('Run without debug option for start detection process');
    }
  };

  module.exports = debugPreprocessor;

}).call(this);
